//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMulti.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sendDeleteToRightOnly {
            get {
                return ((bool)(this["sendDeleteToRightOnly"]));
            }
            set {
                this["sendDeleteToRightOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point lastLocation {
            get {
                return ((global::System.Drawing.Point)(this["lastLocation"]));
            }
            set {
                this["lastLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool onTopWhenInactive {
            get {
                return ((bool)(this["onTopWhenInactive"]));
            }
            set {
                this["onTopWhenInactive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool compactUI {
            get {
                return ((bool)(this["compactUI"]));
            }
            set {
                this["compactUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int numberOfGroups {
            get {
                return ((int)(this["numberOfGroups"]));
            }
            set {
                this["numberOfGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool disableKeepAlive {
            get {
                return ((bool)(this["disableKeepAlive"]));
            }
            set {
                this["disableKeepAlive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public int modeKeyCode {
            get {
                return ((int)(this["modeKeyCode"]));
            }
            set {
                this["modeKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int leftJumpKeyCode {
            get {
                return ((int)(this["leftJumpKeyCode"]));
            }
            set {
                this["leftJumpKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46")]
        public int leftThrowKeyCode {
            get {
                return ((int)(this["leftThrowKeyCode"]));
            }
            set {
                this["leftThrowKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int leftEscapeKeyCode {
            get {
                return ((int)(this["leftEscapeKeyCode"]));
            }
            set {
                this["leftEscapeKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87")]
        public int leftForwardKeyCode {
            get {
                return ((int)(this["leftForwardKeyCode"]));
            }
            set {
                this["leftForwardKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int leftLeftKeyCode {
            get {
                return ((int)(this["leftLeftKeyCode"]));
            }
            set {
                this["leftLeftKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83")]
        public int leftBackKeyCode {
            get {
                return ((int)(this["leftBackKeyCode"]));
            }
            set {
                this["leftBackKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int leftRightKeyCode {
            get {
                return ((int)(this["leftRightKeyCode"]));
            }
            set {
                this["leftRightKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int rightJumpKeyCode {
            get {
                return ((int)(this["rightJumpKeyCode"]));
            }
            set {
                this["rightJumpKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46")]
        public int rightThrowKeyCode {
            get {
                return ((int)(this["rightThrowKeyCode"]));
            }
            set {
                this["rightThrowKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int rightEscapeKeyCode {
            get {
                return ((int)(this["rightEscapeKeyCode"]));
            }
            set {
                this["rightEscapeKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38")]
        public int rightForwardKeyCode {
            get {
                return ((int)(this["rightForwardKeyCode"]));
            }
            set {
                this["rightForwardKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37")]
        public int rightLeftKeyCode {
            get {
                return ((int)(this["rightLeftKeyCode"]));
            }
            set {
                this["rightLeftKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int rightBackKeyCode {
            get {
                return ((int)(this["rightBackKeyCode"]));
            }
            set {
                this["rightBackKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39")]
        public int rightRightKeyCode {
            get {
                return ((int)(this["rightRightKeyCode"]));
            }
            set {
                this["rightRightKeyCode"] = value;
            }
        }
    }
}
