//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTMulti.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool sendDeleteToRightOnly {
            get {
                return ((bool)(this["sendDeleteToRightOnly"]));
            }
            set {
                this["sendDeleteToRightOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point lastLocation {
            get {
                return ((global::System.Drawing.Point)(this["lastLocation"]));
            }
            set {
                this["lastLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool onTopWhenInactive {
            get {
                return ((bool)(this["onTopWhenInactive"]));
            }
            set {
                this["onTopWhenInactive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool compactUI {
            get {
                return ((bool)(this["compactUI"]));
            }
            set {
                this["compactUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int numberOfGroups {
            get {
                return ((int)(this["numberOfGroups"]));
            }
            set {
                this["numberOfGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool disableKeepAlive {
            get {
                return ((bool)(this["disableKeepAlive"]));
            }
            set {
                this["disableKeepAlive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public int modeKeyCode {
            get {
                return ((int)(this["modeKeyCode"]));
            }
            set {
                this["modeKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int leftJumpKeyCode {
            get {
                return ((int)(this["leftJumpKeyCode"]));
            }
            set {
                this["leftJumpKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46")]
        public int leftThrowKeyCode {
            get {
                return ((int)(this["leftThrowKeyCode"]));
            }
            set {
                this["leftThrowKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int leftEscapeKeyCode {
            get {
                return ((int)(this["leftEscapeKeyCode"]));
            }
            set {
                this["leftEscapeKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("87")]
        public int leftForwardKeyCode {
            get {
                return ((int)(this["leftForwardKeyCode"]));
            }
            set {
                this["leftForwardKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int leftLeftKeyCode {
            get {
                return ((int)(this["leftLeftKeyCode"]));
            }
            set {
                this["leftLeftKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("83")]
        public int leftBackKeyCode {
            get {
                return ((int)(this["leftBackKeyCode"]));
            }
            set {
                this["leftBackKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("68")]
        public int leftRightKeyCode {
            get {
                return ((int)(this["leftRightKeyCode"]));
            }
            set {
                this["leftRightKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public int rightJumpKeyCode {
            get {
                return ((int)(this["rightJumpKeyCode"]));
            }
            set {
                this["rightJumpKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("46")]
        public int rightThrowKeyCode {
            get {
                return ((int)(this["rightThrowKeyCode"]));
            }
            set {
                this["rightThrowKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27")]
        public int rightEscapeKeyCode {
            get {
                return ((int)(this["rightEscapeKeyCode"]));
            }
            set {
                this["rightEscapeKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38")]
        public int rightForwardKeyCode {
            get {
                return ((int)(this["rightForwardKeyCode"]));
            }
            set {
                this["rightForwardKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37")]
        public int rightLeftKeyCode {
            get {
                return ((int)(this["rightLeftKeyCode"]));
            }
            set {
                this["rightLeftKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public int rightBackKeyCode {
            get {
                return ((int)(this["rightBackKeyCode"]));
            }
            set {
                this["rightBackKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("39")]
        public int rightRightKeyCode {
            get {
                return ((int)(this["rightRightKeyCode"]));
            }
            set {
                this["rightRightKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public int keepAliveKeyCode {
            get {
                return ((int)(this["keepAliveKeyCode"]));
            }
            set {
                this["keepAliveKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string keyBindings {
            get {
                return ((string)(this["keyBindings"]));
            }
            set {
                this["keyBindings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string leftKeys {
            get {
                return ((string)(this["leftKeys"]));
            }
            set {
                this["leftKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string rightKeys {
            get {
                return ((string)(this["rightKeys"]));
            }
            set {
                this["rightKeys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool runAsAdministrator {
            get {
                return ((bool)(this["runAsAdministrator"]));
            }
            set {
                this["runAsAdministrator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int controlAllGroupsKeyCode {
            get {
                return ((int)(this["controlAllGroupsKeyCode"]));
            }
            set {
                this["controlAllGroupsKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://danfresneda.com/tt/multicontroller")]
        public string homepageUrl {
            get {
                return ((string)(this["homepageUrl"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int individualControlKeyCode {
            get {
                return ((int)(this["individualControlKeyCode"]));
            }
            set {
                this["individualControlKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool replicateMouse {
            get {
                return ((bool)(this["replicateMouse"]));
            }
            set {
                this["replicateMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int replicateMouseKeyCode {
            get {
                return ((int)(this["replicateMouseKeyCode"]));
            }
            set {
                this["replicateMouseKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Size lastGroupsFormSize {
            get {
                return ((global::System.Drawing.Size)(this["lastGroupsFormSize"]));
            }
            set {
                this["lastGroupsFormSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int groupModeKeyCode {
            get {
                return ((int)(this["groupModeKeyCode"]));
            }
            set {
                this["groupModeKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mirrorModeKeyCode {
            get {
                return ((int)(this["mirrorModeKeyCode"]));
            }
            set {
                this["mirrorModeKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool groupModeCycleWithModeHotkey {
            get {
                return ((bool)(this["groupModeCycleWithModeHotkey"]));
            }
            set {
                this["groupModeCycleWithModeHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mirrorModeCycleWithModeHotkey {
            get {
                return ((bool)(this["mirrorModeCycleWithModeHotkey"]));
            }
            set {
                this["mirrorModeCycleWithModeHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool allGroupModeCycleWithModeHotkey {
            get {
                return ((bool)(this["allGroupModeCycleWithModeHotkey"]));
            }
            set {
                this["allGroupModeCycleWithModeHotkey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int mirrorGroupModeKeyCode {
            get {
                return ((int)(this["mirrorGroupModeKeyCode"]));
            }
            set {
                this["mirrorGroupModeKeyCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mirrorGroupModeCycleWithModeHotkey {
            get {
                return ((bool)(this["mirrorGroupModeCycleWithModeHotkey"]));
            }
            set {
                this["mirrorGroupModeCycleWithModeHotkey"] = value;
            }
        }
    }
}
